ALTER TABLE `instruments` ADD `is_valid` VARCHAR(2) NOT NULL DEFAULT 'NV' AFTER `created`; 
ALTER TABLE `reservations` ADD `owner_id` INT NOT NULL AFTER `instrument_id`;
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 2; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 4; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 5; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 7; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 8; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 10; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 11; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 12; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 13; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 16; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 19; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 20; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 21; 
UPDATE `reservations` SET `owner_id` = '71' WHERE `reservations`.`id` = 22; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 23; 
UPDATE `reservations` SET `owner_id` = '72' WHERE `reservations`.`id` = 24;